### ISSUE TITLE
HM2 Zad. 1

### ISSUE THREAD

**Issue by AntonYush** [daftcode/daftacademy-python_levelup-spring2020#13]
Proszę o wyjaśnienie, co musi robić dekorator **wraps** bez żadnych argumentów, który musimy napisać.

Ja rozumiem, jak działa taka konstrukcja:
...
    @wraps(f)
    def inner1(*args, **kwargs):
...
Ale co musi robić taka:
...
    @wraps
    def inner2(*args, **kwargs):
...
?
Jeżeli w pierwszym przypadku np. inner1.__name__ == f.__name__, to czemu musi być równe 
inner2.__name__? Jakim imieniem jego podmieniać?
Dodam jeszcze, że to zadanie może być rozwiązane w bardzo dziwny (bo jest po-pierwsze za łatwy, a po drugie znika jakikolwiek sens użycia tego dekoratora) sposób.

**Comment by AntonYush** [comment]
GitHub ukrył podłogi, oczywiście, że tam jest nie "name", tylko <dwie podłogi>name<dwie podłogi>

**Comment by mateusz94** [comment]
wraps powinien robić to samo co ten z biblioteki standardowej.
Powinien przepisywać część atrybutów metod, żeby nie tracić informacji o tym co jest wywołane.

**Comment by AntonYush** [comment]
> wraps powinien robić to samo co ten z biblioteki standardowej.
> Powinien przepisywać część atrybutów metod, żeby nie tracić informacji o tym co jest wywołane.

Ten z biblioteki standardowej bierze w nawiasach argument - funkcję, skąd musi przepisywać atrybuty (@wraps(funkcja) - te nawiasy z funkcją są obowiązkowe, ale w przykładzie ich nie ma).
Dlatego ponawiam pytanie: w tym drugim przypadku z początku dyskusji skąd atrybuty muszą być przepisywane do inner2, gdyż tego argumentu nie ma?

**Comment by mateusz94** [comment]
w drugim przypadku powinien przepisać atrybuty inner2

**Comment by AntonYush** [comment]
Okej, już nie znam jak jeszcze to wytłumaczyć. Dołączam kod , który robi **dokładnie** to samo, co functools.wraps dla tych kilku atrybutów. Testów to nie przechodzi, co więcej, przy uruchomieniu przykładu z repl.it za pomocą samego functools.wraps, assert wyrzuca błąd.
`def wraps(f_attrs_from):
    def real_decor(f_to_decorate):
        # zdaję sobie sprawę, że f_to_decorate - zmienna lokalna
        f_to_decorate.__name__ = f_attrs_from.__name__
        f_to_decorate.__module__ = f_attrs_from.__module__
        f_to_decorate.__doc__ = f_attrs_from.__doc__
        f_to_decorate.__qualname__ = f_attrs_from.__qualname__
        f_to_decorate.__annotations__ = f_attrs_from.__annotations__
        return f_to_decorate
    return real_decor`

**Comment by mateusz94** [comment]
Pełna zgoda!

**Comment by naboru** [comment]
Brawa za czujność. Mati wprowadz fixa do zadania :)

**Comment by mateusz94** [comment]
Wprowadzone. Poprzednio nadesłane rozwiązania zostały usunięte.
