### ISSUE TITLE
Wykład 2 - Zadanie 2

### ISSUE THREAD

**Issue by Szuumii** [daftcode/daftacademy-python_levelup-spring2020#19]
W treści zadania podane jest, aby w przypadku podania kluczy, które nie znajdują się w dict należy zwrócić None. W przypadku wywołania dekoratora z niepoprawnymi argumentami zaczyna sypać, że zwrócony obiekt nie jest callable. Czy treść zadania jest na pewno poprawna? Co w takim razie zwrócić w przypadku kiedy argumenty nie odpowiadają tym z dictionary funkcji??

**Comment by Szuumii** [comment]
Wydaje mi się, że w teście string w miejsciu assert.isNone nie powinno być wywołania elementu który z założenia ma być typu None

**Comment by vGOOMBAv** [comment]
Treść poprawna
Ja po prostu None zwracałem.

return None

**Comment by mmejer** [comment]
Czy `return None` masz w "najbardziej wewnętrznej" funkcji?

**Comment by vGOOMBAv** [comment]
> Czy `return None` masz w "najbardziej wewnętrznej" funkcji?

Yep

**Comment by mmejer** [comment]
pytanie do @Szuumii, sorki :D

**Comment by Szuumii** [comment]
W takim razie jak w funkcji, która zwraca wywołaną funkcję dekorowaną masz dostęp do argumentów dekoratora? Żeby ustalić czy zwrócić None potrzebujesz mieć args które jest przykrywane w najbardziej wewnętrznej funkcji??

**Comment by Szuumii** [comment]
> Czy `return None` masz w "najbardziej wewnętrznej" funkcji?

Mam jedną instancje wyżej, aby mieć dostęp do args

**Comment by mmejer** [comment]
zamiast `is_correct(*args)`  mam `is_correct(*keys)`

**Comment by mpalka31** [comment]
ten sam pronlem 
`from functools import wraps
def is_correct(*keys):
  def real_decorator(func):
    @wraps(func)
    def wrapper(*args, **kwds):
      result = func(*args, **kwds)
      for key in result:
        if result[key] == None:
          return None
      
      for i in keys:
        flag = False
        for key in result:
          if key == i:
            flag = True
        if flag == False:
          return None
      return result
    return wrapper
  return real_decorator`
co ciekawe w google colab sprawdziłem dla przypadku gdzie nie przechodzi testu i działa

**Comment by mpalka31** [comment]
u mnie to samo 
co dziwne sprawdziłem kod w google colab dla przykładu który nie przecodzi testu, i działa

**Comment by mpalka31** [comment]
na początku sprawdź czy słownik jest pusty, jeśli tak to zwróć słownik z wartością None (np: {None: None})
