### ISSUE TITLE
Termin realizacji zadań z wykładu numer 2

### ISSUE THREAD

**Issue by Edyta-Kaleta** [daftcode/daftacademy-python_levelup-spring2020#20]
Hej, 
chciałam zapytać dlaczego termin realizacji zadań z wykładu numer 2 jest inny dla zadania numer 1 (14 kwietnia, 09:59) i dla zadania numer 2 i 3 (13 kwietnia, 09:59)? Czy to jest celowe?
Zasugerowałam się terminem dla zadania numer 1 (które wykonałam wcześniej) i myślałam, że taki sam termin jest ustalony dla zdania zadania numer 2 i 3? Niestety pozostałe dwa wykonałam dopiero teraz. Czy istnieje możliwość by wszystkie zostały uznane? Czy to było jednak celowe działanie.
Będę wdzięczna za odpowiedź. 
PS Wesołych świąt!
Edyta

**Comment by mixedpixel** [comment]
Same here ;) 
Ten świąteczny deadline to chyba w ogóle troszkę słaby pomysł imho
Piotrek

**Comment by mateusz94** [comment]
Cześć,
Data oddania pierwszego zadania była inna, ponieważ w zadaniu był błąd odnaleziony we wtorek.

**Comment by m-kowalewski** [comment]
A czy w związku ze świętami i brakiem wykładu, jest możliwość przesunięcia daty oddania wszystkich zadań?

**Comment by mateusz94** [comment]
Tak, przedłużyłem termin oddania do najbliższego wykładu.
Dobrego dnia!
