### ISSUE TITLE
Wykład 3, zadanie 3

### ISSUE THREAD

**Issue by Calvitium** [daftcode/daftacademy-python_levelup-spring2020#27]
Czy ktoś mógłby mi pomóc? Nie wiem, z jakiego powodu logout nie przepuszcza testu na autoryzację przy takiej implementacji /login: 

```python
### TASK 2 ###########################################################
from hashlib import sha256
from starlette.responses import RedirectResponse
from fastapi.security import HTTPBasic, HTTPBasicCredentials
from fastapi import Depends, Response
import secrets

security = HTTPBasic()
app.secret_key = "very constatn and random secret, best 64 characters, here it is."

session_tokens = []

@app.post("/login")
def get_current_user(response: Response, credentials: HTTPBasicCredentials = Depends(security)):
    correct_username = secrets.compare_digest(credentials.username, "trudnY")
    correct_password = secrets.compare_digest(credentials.password, "PaC13Nt")
    if not (correct_username and correct_password):
        raise HTTPException(status_code=401, detail="Incorrect email or password")
    session_token = sha256(bytes(f"{credentials.username}{credentials.password}{app.secret_key}", encoding='utf8')).hexdigest()
    response.set_cookie(key="session_token", value=session_token)
    session_tokens.append(session_token)
    return RedirectResponse(url='/welcome')	

### TASK 3 ###########################################################
from fastapi import Cookie

@app.post("/logout")
def logout(*, response: Response, session_token: str = Cookie(None)):
	if session_token not in session_tokens:
		raise HTTPException(status_code=401, detail="Unathorised")
	session_tokens.delete(session_token)
	return RedirectResponse("/")
```python

**Comment by mateusz94** [comment]
Spróbuj proszę ustawić sobie jedenego workera: https://github.com/daftcode/daftacademy-python_levelup-spring2020/issues/24

**Comment by Calvitium** [comment]
Niestety po dopisaniu do Procfile --workers 1, błąd ciągle ten sam: 

Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 29, in test_test_logout
    self.assertTrue(r2.status_code in  (307, 301, 302, 303))
AssertionError: False is not true

Będę wdzięczny za pomoc

https://github.com/Calvitium/d_jak_deploy

**Comment by mateusz94** [comment]
podaj proszę URLa do swojej apki

**Comment by Calvitium** [comment]
https://dashboard.heroku.com/docs

**Comment by mateusz94** [comment]
hehe, nie zwracasz ciasteczka :)

curl -X POST "https://diploj.herokuapp.com/login" -H  "accept: application/json" --user trudnY:PaC13Nt -vv

**Comment by Calvitium** [comment]
Okej, dzięki, myślałem, że to ciasteczko samo się zwraca w tym response. W takim razie mógłbym liczyć na jakiegoś małego hinta?

**Comment by mateusz94** [comment]
hm, zobacz, nie zwracasz `response`, do którego zapisujesz ciasteczko, tylko nowy obiekt `RedirectResponse`, który go nie ma.

**Comment by Calvitium** [comment]
O matulu, zorientowałem się zaraz po zadaniu tego pytania. Tak czy siak, dzięki za szybką odpowiedź!
