### ISSUE TITLE
Wykład 3, zadanie 4

### ISSUE THREAD

**Issue by Calvitium** [daftcode/daftacademy-python_levelup-spring2020#28]
Tak wygląda moja templatka: 

```html
<html>
<body>
    <h1 id="greeting">Hello, {{user}}!</h1>
</body>
</html>
```
Mimo to, test rzuca błędem, jakoby w HTML-u nie było    'id="greeting"'. Ktoś coś?

**Comment by BartlomiejRasztabiga** [comment]
@Calvitium i co było problemem?

**Comment by AndrewMatviichuk** [comment]
Jaj rozwiązałeś ten problem?

**Comment by BartlomiejRasztabiga** [comment]
@AndrewMatviichuk odpal ponownie testy na repl.it, u mnie dzisiaj przeszły

**Comment by AndrewMatviichuk** [comment]
> @AndrewMatviichuk odpal ponownie testy na repl.it, u mnie dzisiaj przeszły

Już próbowałem. Mam taki samy html, jak u ciebie. Nie wiem dla czego nie przechodzi testu.

**Comment by Calvitium** [comment]
W moim przypadku problemem był fakt, że słownik z kluczami przekazywany generatorowi templatek musi zawierać w sobie klucz "request" oraz odpowiednią wartość typu Request. Tak więc: 
```python
return templates.TemplateResponse("item.html", {"request": request, "user": "trudnY"})
```
Korzystam z Jinja.

**Comment by AndrewMatviichuk** [comment]
> W moim przypadku problemem był fakt, że słownik z kluczami przekazywany generatorowi templatek musi zawierać w sobie klucz "request" oraz odpowiednią wartość typu Request. Tak więc:
> 
> ```python
> return templates.TemplateResponse("item.html", {"request": request, "user": "trudnY"})
> ```
> 
> Korzystam z Jinja.

Już działa. Problem był w tym, że mój program niepoprawnie obsługiwał ciasteczka.

**Comment by AndrewMatviichuk** [comment]
> W moim przypadku problemem był fakt, że słownik z kluczami przekazywany generatorowi templatek musi zawierać w sobie klucz "request" oraz odpowiednią wartość typu Request. Tak więc:
> 
> ```python
> return templates.TemplateResponse("item.html", {"request": request, "user": "trudnY"})
> ```
> 
> Korzystam z Jinja.

Dziękuję za pomoc!

**Comment by Mcrackers** [comment]
Pomimo zastosowania powyższych wskazówek moja aplikacja nadal nie przechodzi testów "body" wyrzucając błąd jakby nie było "greetings". Czy ktoś ma jeszcze inne rozwiązanie?

**Comment by AndrewMatviichuk** [comment]
> Pomimo zastosowania powyższych wskazówek moja aplikacja nadal nie przechodzi testów "body" wyrzucając błąd jakby nie było "greetings". Czy ktoś ma jeszcze inne rozwiązanie?

Sprawdź czy poprawnie obsługujesz cookies, a potem przez postman sprawdź cały funkcjonał aplikacji
