### ISSUE TITLE
Repl.it zad 4 test

### ISSUE THREAD

**Issue by Wincioor11** [daftcode/daftacademy-python_levelup-spring2020#3]
Cześć,
Mam problem z zadaniem 4 z pierwszej pracy domowej. Dodałem funkcjonalność, przetestowałem w Postmanie i wszystko działa jak należy, tzn pacjenci się dodają i można ich getować. Jeżeli pacjent o podanym id nie istnieje to zwracany jest Response(status_code=204). 
Test, który nie przychodzi:
![image](https://user-images.githubusercontent.com/38164733/78026867-9e67a700-735c-11ea-917b-ed50b75ce195.png)

Przejrzałem details i wychodzi na to , że test próbuje parsować puste response body na jsona i byłoby to łatwe do zmienienia w kodzie,  gdyby nie fakt, że w fastapi response'y ze status_code=204 mają ustawioną Content-Length = 0 i nie da się zwrócić żadnego json body. 
Jakaś podpowiedź ?

**Comment by mateusz94** [comment]
Spróbuj wykonać test raz jeszcze.

Test najpierw tworzy kilku pacjentów, a potem sprawdza, czy istneje. Mogło się zdarzyć, że podczas testu nastąpiło przeładowanie Twojej aplikacji, przez co zmienił się jej stan.

**Comment by Mishioo** [comment]
Możesz wymusić odpowiedź w formacie JSON, bezpośrednio zwracając pusty JSONResponse:
`from fastapi.responses import JSONResponse`
a później w odpowiedniej funkcji
`return JSONResponse(status_code=204, content={})`
Rzuć okiem na [tę część dokumentacji](https://fastapi.tiangolo.com/advanced/response-directly/).

**Comment by Wincioor11** [comment]
> Możesz wymusić odpowiedź w formacie JSON, bezpośrednio zwracając pusty JSONResponse:
> `from fastapi.responses import JSONResponse`
> a później w odpowiedniej funkcji
> `return JSONResponse(status_code=204, content={})`
> Rzuć okiem na [tę część dokumentacji](https://fastapi.tiangolo.com/advanced/response-directly/).

Próbowałem na kilka sposobów, ale wtedy nawet lokalnie wypluwał ERROR, że za duża długość content'u. 
Spróbowałem dokładnie tak samo jak zaproponowałeś i uvicorn wyrzuca: 
"h11._util.LocalProtocolError: Too much data for declared Content-Length"

**Comment by mateusz94** [comment]
@Wincioor11 a czy zapisujesz gdzieś pacjeta?

**Comment by Wincioor11** [comment]
> @Wincioor11 a czy zapisujesz gdzieś pacjeta?

Tak, w liście globalnej. Zapisywanie i odczyt działa. Testowałem już zdeployowane api uzywając postmana. 
Testy na repl.it wywalają się na :

> Traceback (most recent call last):
>   File "/home/runner/unit_tests.py", line 26, in test_response_structure
>     res = resp.json()
(...)

> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mateusz94** [comment]
Jaki numer ma pierwszy wpisany pacjent?

**Comment by Wincioor11** [comment]
> Jaki numer ma pierwszy wpisany pacjent?

Faktycznie, złe założenie działania 'przychodni'. Debugging o 3AM nie jest najskuteczniejszy Dzięki!

**Comment by mateusz94** [comment]
Proszę bardzo!
