### ISSUE TITLE
Wykład 4, zadanie 3 - błąd w testach na repl.it

### ISSUE THREAD

**Issue by Obsttube** [daftcode/daftacademy-python_levelup-spring2020#38]
Hej, w testach do zadania 3 jest błąd.
W treści zadania napisane jest, żeby zwracać:
```
{
    "AlbumId": int,
    "Title": str,
    "ArtistId": int
}
```
Tymczasem, gdy zwraca się taki response, pojawia się błąd:
### get_album_200
```
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 49, in test_get_album_200
    resp = response.json()[0]
KeyError: 0
```

Okazuje się, że gdy zwróci się: (niezgodnie z treścią zadania)
```
[{
    "AlbumId": int,
    "Title": str,
    "ArtistId": int
}]
```
To testy przechodzą bezbłędnie.

Domyślam się, że użycie [0] w testach było spowodowane użyciem `.fetchall()` zamiast `.fetchone()` w kodzie, który był przez was testowany.

Naprawienie testów to kwestia zmiany wystąpień `resp = response.json()[0]` na `resp = response.json()`

**Comment by DziurewiczPiotr** [comment]
Dzięki @Obsttube ! Testy poprawione.
