### ISSUE TITLE
Wykład 4, zadanie 3

### ISSUE THREAD

**Issue by skala90** [daftcode/daftacademy-python_levelup-spring2020#41]
Przy teście ``get_album_200`` mam błąd:

``assert response.status_code == 200
AssertionError``

i próbuję zrobić ten test ręcznie przez Swaggera, czyli:

POST na /album:
``{"title": "Mandaryna HITS", "artist_id": 1}``

potem ze zwrotki wybieram ``AlbumId`` i puszczam GET /album/XX

response ze statusem 200:

```
{
  "AlbumId": 351,
  "Title": "Mandaryna HITS",
  "ArtistId": 1
}
```
URL aplikacji: https://skala-daft-1.herokuapp.com/

**Comment by DziurewiczPiotr** [comment]
Hej @skala90 !

Twój endpoint POST https://skala-daft-1.herokuapp.com/albums zwraca poprawnie obiekt:

```
{
    "AlbumId": 355,
    "Title": "Mandaryna HITS",
    "ArtistId": 1
}
```

jednak endpoint GET https://skala-daft-1.herokuapp.com/albums/355 zwraca:

```
{
    "detail": "Not Found"
}
```

**Comment by skala90** [comment]
Dziękuję pomogło:) 
Okazało się, że wkradła się literówka i zamiast ``albums`` miałam ``album``.
