### ISSUE TITLE
Wyk 4 zad 1 aplikacja nie może przejść testu 'assert raw data'

### ISSUE THREAD

**Issue by AvaRat** [daftcode/daftacademy-python_levelup-spring2020#42]
Wszystkie testy w zadaniu 1 mi przechodzą oprócz tego, a nic nie edytowałem w bazie z linku. Mam więc podejrzenia, że źle zinterpretowałem parametry. Z tego co rozumiem, to per_page to ilość wierszy które mamy wyświetlić, a page to numer wiersza od którego zacząć. Czyli robię prosty SELECT i na koniec LIMIT {per_page} OFFSET page}. Dajcie znać, czy to brzmi sensownie, czy źle to zrozumiałem, bo nie mogę tego testu zrobić.

**Comment by jakubmatyszewski** [comment]
Za pomocą `per_page` definiujesz ilość wierszy na stronie.
Atrybut `page` natomiast mówi o tym ile stron (zawierających `per_page` wierszy) chcesz ominąć.
Zatem OFFSET powinno się liczyć jako `page * per_page`.

**Comment by AvaRat** [comment]
Dzięki. Już działa
