### ISSUE TITLE
Wyklad 4 Zadanie 4 - problem z poprawna odpowiedzia

### ISSUE THREAD

**Issue by JAJA1706** [daftcode/daftacademy-python_levelup-spring2020#44]
Mam problem z zaliczeniem testu put_customer_success_200 i put_customer_raw_data_success_200.
Widze w konsoli heroku ze aplikacja odpowiada kodem 200 wiec problem musi byc w tym jaka jest odpowiedz. Tylko ze patrzac na odpowiedz dawana przez swaggera wszystko wydaje sie ok:

![lol](https://user-images.githubusercontent.com/58956120/80978549-7e794680-8e26-11ea-9083-663a7744eea5.png)

czy ktos zaliczyl to zadanie i moglby podsunac pomysl co moze byc nie tak?
Mi jedynie co nie zgadza sie z sugerowana odpowiedzia na repl.it to to, ze po ostatnim wierszu w odpowiedzi powinien pojawic sie przecinek, a u mnie go nie ma, ale watpie, ze przez to nie przechodzilyby testy.

**Comment by Szuumii** [comment]
Podłączam się do pytania

**Comment by DziurewiczPiotr** [comment]
Hejka! @Szuumii @JAJA1706 
Podajcie urle do swoich aplikacji

**Comment by JAJA1706** [comment]
> Hejka! @Szuumii @JAJA1706
> Podajcie urle do swoich aplikacji

https://daftcodepracadom.herokuapp.com/

**Comment by DziurewiczPiotr** [comment]
@JAJA1706 
Twoja apka z urla:
```
PUT https://daftcodepracadom.herokuapp.com/customers/{id}
```
po dodaniu do body jsona:

```
{
	"city": "supercity",
	"state": "superstate"
}
```
zwraca:
```
.
.
.
    "City": "Paris",
    "State": null,
.
.
.
```

**Comment by JAJA1706** [comment]
Ahh pola mojego body zaczynaly sie z duzych liter w tym tkwil problem. Dzieki wielkie.

**Comment by Szuumii** [comment]
> Hejka! @Szuumii @JAJA1706
> Podajcie urle do swoich aplikacji

https://withdbpage.herokuapp.com/

**Comment by DziurewiczPiotr** [comment]
> > Hejka! @Szuumii @JAJA1706
> > Podajcie urle do swoich aplikacji
> 
> https://withdbpage.herokuapp.com/

U ciebie ten sam problem co u @JAJA1706
