### ISSUE TITLE
Wykład 4 - zadanie 1

### ISSUE THREAD

**Issue by Szuumii** [daftcode/daftacademy-python_levelup-spring2020#48]
Nie przechodzi mi test assert_raw_data pomimo tego, że na docs dane się zgadzają. Prawdopodobnie chodzi tutaj o indeksowanie. Ktoś może spotkał się już z tym błędem? 

SQL-ka : data = app.db_connection.execute(
        "SELECT * FROM tracks ORDER BY TrackId ASC LIMIT ? OFFSET ?;"       , (per_page, page)).fetchall()

**Comment by DziurewiczPiotr** [comment]
Hej! @Szuumii 
Nie działa u Ciebie dobrze podział na strony. Zwracasz nie te co trzeba.

**Comment by Szuumii** [comment]
@DziurewiczPiotr 
Uzyskuję ten sam wynik co w teście po wpisaniu wartości dla zmiennych per_page = 2 i page = 6.
Rozumiem, że dane zostaną poprawnie zwrócone dla wartości per_page = 2 i page = 7 ?

**Comment by DziurewiczPiotr** [comment]
Generalnie źle masz napisany podział na strony. #42
