### ISSUE TITLE
Wykład 4 - zadanie 5 

### ISSUE THREAD

**Issue by Szuumii** [daftcode/daftacademy-python_levelup-spring2020#49]
Czy suma którą powinniśmy zwracać w odpowiedzi to wartość z kolumny Total z tabeli invoices? Nie przechodzi mi test assert_raw_data i zastanawiam się czy zwróciłem dobrą kolumnę? 
Moja strona: https://withdbpage.herokuapp.com/

**Comment by DziurewiczPiotr** [comment]
@Szuumii 
Z tego co widzę zwracasz nie sumę wydatków tylko jakąś sumę, albo wartość pojedynczej transakcji customera. Musisz wziąć pod uwagę wszystkie transakcje z `invoices`
