### ISSUE TITLE
praca domowa 1 zadanie 3 apka nie przechodzi testów

### ISSUE THREAD

**Issue by mpalka31** [daftcode/daftacademy-python_levelup-spring2020#8]
Mój kod : 

app.counter = 0

class Patient(BaseModel):
....name: str
....surename: str

class Response(BaseModel):
....id: int
....patient: Patient

@app.post("/patient",response_model=Response)
def patient_position(pt: Patient):
....app.counter += 1
....return Response(id=app.counter,patient=pt)

Na repl.it wszystkie testy mi wywala a wydaje się że wszystko dobrze zwraca. 
Jakby mi ktoś podpowiedział dco mam źle to był bym wdzięczny bi już długo nad tym siedzę i nie mogę nic mądrego wymyślić.

ps. sory za to nieeleganckie wstawienie kodu ale formatowanie mi nie chce działać jakoś

**Comment by kulakowski-lukasz** [comment]
Podpinam się, też mam problem, jednak u mnie nie przechodzi tylko ostatniego testu **idki**

Link do apki: https://lk-djakdeploy.herokuapp.com/
Link do gita: https://github.com/kulakowski-lukasz/d_jak_deploy

Info z testu na którym się wykładam:
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 46, in test_idki
    self.assertTrue(len({result["id"] for result in self.my_results}) > 1)
AssertionError: False is not true

**Comment by mpalka31** [comment]
@kulakowski-lukasz masz problem z licznikiem chyba w takim razie, skorzystaj z app.counter, u mnie już przeszło testy. Okazało się że to repl.it się zwiesił i trzeba było odświeżyć xD

**Comment by kulakowski-lukasz** [comment]
@mpalka31 zmieniłem na counter i z perspektywy /docs jak sobie puszczam testowo post to id się zwiększa, ale test **idki** dalej nie przechodzi :( Bajdełej - skąd ten counter? Mogę prosić o jakieś źródło? Czy to jest metoda FastApi?

**Comment by kulakowski-lukasz** [comment]
@mpalka31 Zmieniłem Reponse tak jak u Ciebie tzn. tam gdzie jest patient : Patient wcześniej miałem dict i zwracałem parient=pt.dict(), po takich poprawkach testy poszły, counter działał ale może cały return miał złą strukturę. Można zamykać! 😀
